import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from './Providers';
import Nav from './components/Nav/Nav';
import styles from './layout.module.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'automatico',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${styles.layout}`}>
        <Nav />
        <div className={styles.innerWrapper}>
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
